//localhost

//clients
###
GET http://localhost:3000/clients

###
GET http://localhost:3000/clients/brad.taylor@gmail.com

### 
POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "firstName": "Mark",
    "lastName": "Taylor",
    "email": "markk.taylor@gmail.com",
    "telephone": "1112223333",
    "address1": "7723 1st Ave",
    "address2": "",
    "city": "Los Angeles",
    "state": "CA",
    "zipcode": "90001"
}

###
PUT http://localhost:3000/clients/634a4ff6adf6d980eeac4456 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
    "lastName": "Smith",
    "email": "j.smith@gmail.com",
    "telephone": "8189874412",
    "address1": "124 Sycamore Drive",
    "address2": "",
    "city": "Reseda",
    "state": "CA",
    "zipcode": "91355"  
}

###
DELETE http://localhost:3000/clients/635cdfba7c25ab671b51eb5d HTTP/1.1

//Inventory
### 
GET http://localhost:3000/inventory

### 
GET http://localhost:3000/inventory/954147

### 
POST http://localhost:3000/inventory HTTP/1.1
Content-Type: application/json 

{
  "productName": "Star Wars: A New Hope",
  "sku": "769904",
  "genre": "Sci-Fi",
  "price": "29.99",
  "quantity": "15"
}

### 
PUT http://localhost:3000/inventory/634b63046e679c93466afd4d HTTP/1.1
Content-Type: application/json

{
  "productName": "The Lord of the Rings: The Two Towers",
  "sku": "",
  "genre": "Sci-Fi",
  "price": "24.99",
  "quantity": "12"
}

###
DELETE http://localhost:3000/inventory/634b63046e679c93466afd4d HTTP/1.1

//Orders

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/634b8218f51ed18d6235c162

### 
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json 

{
  "clientId": "634a4ff6adf6d980eeac4456",
  "sku": "354777",
  "price": "27.99",
  "quantity": "2",
  "total": "55.98"
}

### 
PUT http://localhost:3000/orders/636215dad4c4b20886124386 HTTP/1.1
Content-Type: application/json

{
  "clientId": "634a5232adf6d980eeac4458",
  "sku": "354777",
  "price": "27.99",
  "quantity": "3",
  "total": "83.97"
}

###
DELETE http://localhost:3000/orders/636215dad4c4b20886124386 HTTP/1.1

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//production
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//clients

### 
GET https://cse-341-project2-week5.onrender.com/clients

###
GET https://cse-341-project2-week5.onrender.com/clients/brad.taylor@gmail.com


###
POST https://cse-341-project2-week5.onrender.com/clients HTTP/1.1
Content-Type: application/json

{
    "firstName": "Tim",
    "lastName": "Taylor",
    "email": "timbo@gmail.com",
    "telephone": "3105551123",
    "address1": "7723 1st Ave",
    "address2": "",
    "city": "Los Angeles",
    "state": "CA",
    "zipcode": "90001"
}

###
PUT https://cse-341-project2-week5.onrender.com/clients/634a4ff6adf6d980eeac4456 HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
    "lastName": "Smith",
    "email": "smith.j@gmail.com",
    "telephone": "818-909-1234",
    "address1": "2334 Elk Drive",
    "address2": "#4",
    "city": "Reseda",
    "state": "CA",
    "zipcode": "93049"
}

### 
DELETE https://cse-341-project2-week5.onrender.com/clients/634a5232adf6d980eeac4458 HTTP/1.1


//Inventory

###
GET https://cse-341-project2-week5.onrender.com/inventory

###
GET https://cse-341-project2-week5.onrender.com/inventory/954147

### 
POST https://cse-341-project2-week5.onrender.com/inventory HTTP/1.1
Content-Type: application/json 

{
  "productName": "Star Wars: A New Hope",
  "sku": "769-904",
  "genre": "Science Fiction",
  "price": "29.99",
  "quantity": "15"
}

###
PUT https://cse-341-project2-week5.onrender.com/inventory/634b65126e679c93466afd51 HTTP/1.1
Content-Type: application/json

{
  "productName": "The Hobbit: The Battle of the Five Armies",
  "sku": "385-727",
  "genre": "Fantasy Adventure",
  "price": "27.99",
  "quantity": "21"
}

###
DELETE https://cse-341-project2-week5.onrender.com/inventory/634b95ebf51ed18d6235c165 HTTP/1.1


//Orders

###
GET https://cse-341-project2-week5.onrender.com/orders

### 
GET https://cse-341-project2-week5.onrender.com/orders/634b8218f51ed18d6235c162

###
POST https://cse-341-project2-week5.onrender.com/orders HTTP/1.1
Content-Type: application/json 

{
  "clienId": "634a4ff6adf6d980eeac4456",
  "sku": "354-777",
  "price": "27.99",
  "quantity": "2",
  "total": "55.98"
}

###
PUT https://cse-341-project2-week5.onrender.com/orders/634b8218f51ed18d6235c162 HTTP/1.1
Content-Type: application/json

{
  "clienId": "634a4ff6adf6d980eeac4456",
  "sku": "874-561",
  "price": "19.99",
  "quantity": "3",
  "total": "59.97"
}

###
DELETE https://cse-341-project2-week5.onrender.com/orders/634b8218f51ed18d6235c162 HTTP/1.1