//localhost

//clients
###
GET http://localhost:3000/clients

###
GET http://localhost:3000/clients/634a4ff6adf6d980eeac4456

###
GET http://localhost:3000/clients/634a5232adf6d980eeac4458

### 
POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "firstName": "Tim",
    "lastName": "Taylor",
    "email": "timbo@gmail.com",
    "telephone": "310-555-1123",
    "address1": "7723 1st Ave",
    "address2": "",
    "city": "Los Angeles",
    "state": "CA",
    "zipcode": "90001"
}

###
PUT http://localhost:3000/clients/634a4ff6adf6d980eeac4456 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Johnny",
    "lastName": "Smith",
    "email": "j.smith@gmail.com",
    "telephone": "818-987-4412",
    "address1": "124 Sycamore Drive",
    "address2": "",
    "city": "Reseda",
    "state": "CA",
    "zipcode": "91355"  
}

###
DELETE http://localhost:3000/clients/634b2f5ea42cea3ce3f21e68 HTTP/1.1

//Inventory
### 
GET http://localhost:3000/inventory

### 
GET http://localhost:3000/inventory/634b63676e679c93466afd4e

### 
POST http://localhost:3000/inventory HTTP/1.1
Content-Type: application/json 

{
  "productName": "Star Wars: A New Hope",
  "sku": "769-904",
  "genre": "Science Fiction",
  "price": "29.99",
  "quantity": "15"
}

### 
PUT http://localhost:3000/inventory/634b60c96e679c93466afd4c HTTP/1.1
Content-Type: application/json

{
  "productName": "The Lord of the Rings: The Fellowship of the Ring",
  "sku": "874-561",
  "genre": "Fantasy Adventure",
  "price": "19.99",
  "quantity": "10"
}

###
DELETE http://localhost:3000/inventory/634b7b004a37eed3547dd31a HTTP/1.1

//Orders

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/634b8218f51ed18d6235c162

### 
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json 

{
  "clienId": "634a5232adf6d980eeac4458",
  "sku": "354-777",
  "price": "27.99",
  "quantity": "2",
  "total": "55.98"
}

### 
PUT http://localhost:3000/orders/634b8ce1caec643b5c8dc59a HTTP/1.1 
Content-Type: application/json

{
  "clienId": "634a5232adf6d980eeac4458",
  "sku": "354-777",
  "price": "27.99",
  "quantity": "3",
  "total": "83.97"
}

###
DELETE http://localhost:3000/orders/634b8ce1caec643b5c8dc59a HTTP/1.1

//production